title: Web Design Class
description: Front end website project for web design class using TypeScript, HTML and CSS.
theme: jekyll-theme-cayman
baseurl: "/FervorWeb"
url: "https://milkeles.github.io"
exclude:
  - site/
  
header_links:
  - name: Go to site
    url: /
  - name: Project Brief
    url: /docs/